name: Build and Deploy

on:
  push:
    branches:
      - main # This workflow runs every time you push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Replace API URL Placeholder 🔁
        run: |
          sed -i "s|__API_URL__|${{ secrets.API_BASE_URL }}|g" script.js
        
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

